### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by arigroisman** [JinhangZhu/supervisely-to-darknet#1]
Hi, I'm running the code and getting this error. Any idea how to solve it? Thanks!

```
Traceback (most recent call last):
  File "convert.py", line 154, in <module>
    val_size = opt.val_size
  File "convert.py", line 128, in convert_supervisely_json
    data_f.write('train={}\n'.format(sets_paths['train']))   # Path of train set
KeyError: 'train'
```

**Comment by JinhangZhu** [comment]
Hi @arigroisman! You are receiving this error because of a wrong argument in the command: `-o` or `--origin`. Suppose you have unzipped the Supervisely file and you are under the directory where `meta.json` locates, you may find another folder called `images` or `xxx`. Then put the name as `--origin` argument, like: `-o images`.

Days ago I found this error too and I deduced that Supervisely had changed the default name of the folder parallel to `meta` from the project name to `images`. 

Hope my reply would help you out.

**Comment by JinhangZhu** [comment]
Hi, @arigroisman could please remind me if the solution work?
